project_id = "hqjlldqtasyzfpirnrnp"

[functions.chat-ai]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.admin-users]
verify_jwt = false